### ISSUE TITLE
How to remove the letter "P" of Phylum from my plots of Diversity Analysis

### ISSUE THREAD

**Issue by OliviaRN** [OliviaRN/Bioinformatics-Questions#1]
After doing the Alpha Diversity analysis in order to see how the diversity of fungi present in the rhizosphere differs between corn fields planted with native and hybrid corn, I got a plot by phyla. What I would like to get is the same graph, but without the letter P which is present in the legend. 

e.g  P_Ascomycota  I just want Ascomycota

This is my code
```
## To Plot OTU Richness like in GUN. Observed Phyla and Time###

sample_data(binary_table_SC)$Time
sample_data(binary_table_SC)$Time <- as.factor(sample_data(binary_table_SC)$Time)
levels(sample_data(binary_table_SC)$Time)<-c("Agosto", "Junio", "Octubre")

sample_data(binary_table_SC)$Time
sample_data(binary_table_SC)$Time<- factor(sample_data(binary_table_SC)$Time, levels = c("Junio", "Agosto", "Octubre"))
sample_data(binary_table_SC)$Time


plot_bar(binary_table_SC, "Treatment", fill = "Phylum") +
  geom_bar(aes(color = Phylum, fill = "Phylum"), stat = "identity", position = "stack") + 
  facet_wrap("Time") +
  ylab("Riqueza de OTU") + 
  theme_classic() +  
  scale_x_discrete(labels=c("Hibrido" = "Maíz Híbrido", "Nativo" = "Maíz Nativo")) +
  theme(text = element_text(size = 10)) + 
  xlab("Tipo de Maíz") + 
  scale_fill_manual(labels = c("Phylum"))
```

Could you help me with this issue pleas?

**Comment by AliciaMstt** [comment]
Lets try removing it directly from the binary table:

```
#Remove "p__" form taxonomic data
tax_table(binary_table_SC)<-gsub("p__", "", tax_table(binary_table_SC))
```

**Comment by OliviaRN** [comment]
To understand the error message that appeared and how gsub works out, Alicia explained me these steps

tax_table(binary_table_SC)
head(tax_table(binary_table_SC))
class(tax_table(binary_table_SC))

x<-as.data.frame(tax_table(binary_table_SC))

x$Phylum

phylums<-unique(x$Phylum)

#### remove
phylums_clean<-gsub("p__", "", phylums)

gsub("p__", "", tax_table(binary_table_SC)

#Remove "p__" form taxonomic data
tax_table(binary_table_SC)<-gsub("p__", "", tax_table(binary_table_SC))
