### ISSUE TITLE
How to reorder the months in ascending order and by treatment in my ANOVA analysis?

### ISSUE THREAD

**Issue by OliviaRN** [OliviaRN/Bioinformatics-Questions#3]
I would like to have better graphics in my ANOVA analysis, I want the months to appear in the correct order (June, August, October) as well as the Treatment (Hybrid vs Landrace maize).  I hope you can help me with your valuable comments :D 

I got this ANOVA plot for all the Fungus 
 
![Captura de Pantalla 2021-04-09 a la(s) 10 51 33](https://user-images.githubusercontent.com/36178935/114207298-d9ae9580-9921-11eb-92f6-25fd16abef5c.png)

This is the ANOVA plot just for the HMA (Glomeromycota)

![Captura de Pantalla 2021-04-09 a la(s) 10 52 41](https://user-images.githubusercontent.com/36178935/114207451-006ccc00-9922-11eb-89db-b335f0f19554.png)

![Captura de Pantalla 2021-04-09 a la(s) 11 49 09](https://user-images.githubusercontent.com/36178935/114214250-b2f45d00-9929-11eb-8927-9e8ab50dd679.png)

My code in R for Fungus was this:

```
############################ A N O V A #################################

diversity <-estimate_richness(binary_table_SC, measures =c("Observed","Fisher"))
diversity

data <-cbind(sample_data(binary_table_SC), diversity)
data

##Data Anova by Treatment

#To know the Diversity Observed by Treatment
Div_Obs<-aov(Observed~Treatment, data = data)
summary(Div_Obs)

#Using FISHER To know the Diversity by Treatment 

Div_Fish<-aov(Fisher~Treatment, data = data) 
summary(Div_Fish)
boxplot(Fisher~Treatment, data = data)

#Data anova by Treatment and Time

anova<-aov(Fisher ~ Time * Treatment, data = data)
summary(anova)
boxplot(Fisher ~ Time * Treatment, data = data)
```

**Comment by OliviaRN** [comment]
Updated w the head (data)

**Comment by AliciaMstt** [comment]
Try with: 

https://www.researchgate.net/post/How_does_one_change_the_order_of_groups_in_boxplots

**Comment by OliviaRN** [comment]
I tried to follow the example of the blog, but it did not workout  (Honestly it was not clear for me some of the directions given in the example, such as the use of the <seq> command. Anyway I ran the commands using most of the same variable names as follows:


#To check what seq does

Generate regular sequences. seq is a standard generic with a default method. seq.int is a primitive which can be much faster but has a few restrictions. seq_along and seq_len are very fast primitives for two common cases.

#To Ordering my boxplot

#I have 

#### "Agosto.Hibrido", "Junio.Hibrido", "Octubre.Hibrido", "Agosto.Nativo", "Junio.Nativo", "Octubre.Nativo"

#I want

#levels(data)<-("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo")

```
mydata2 <- data.frame(data = seq(), 
va2 = as.factor(data(c("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo", replace = TRUE))))
mydata2$va3 <- (mydata2$va2, levels=levels(mydata2$va2)<-c("Agosto.Hibrido", "Junio.Hibrido", "Octubre.Hibrido", "Agosto.Nativo", "Junio.Nativo", "Octubre.Nativo"))
levels(mydata2$va2)<-c("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo"))
boxplot(mydata2$data~mydata2$va3, main="va3")
boxplot(mydata2$data~mydata2$va2, main="va2")
```

After running it, the next Error Messages appeared:

![Captura de Pantalla 2021-04-16 a la(s) 10 35 45](https://user-images.githubusercontent.com/36178935/115048848-a6c74d00-9e9f-11eb-87c1-f122dda50139.png)

```
Warning message:
In data(c("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo",  :
  data set ‘c("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo", replace = TRUE)’ not found
> mydata2$va3 <- (mydata2$va2, levels=levels(mydata2$va2)<-c("Agosto.Hibrido", "Junio.Hibrido", "Octubre.Hibrido", "Agosto.Nativo", "Junio.Nativo", "Octubre.Nativo"))
Error: unexpected ',' in "mydata2$va3 <- (mydata2$va2,"
> levels(mydata2$va2)<-c("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo"))
Error: unexpected ')' in "levels(mydata2$va2)<-c("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo"))"
> boxplot(mydata2$data~mydata2$va3, main="va3")
Error in model.frame.default(formula = mydata2$data ~ mydata2$va3) : 
  invalid type (NULL) for variable 'mydata2$va3'
> boxplot(mydata2$data~mydata2$va2, main="va2")

```

Please, could you help me to review it today in our meeting?

Thanks in advance :)

**Comment by OliviaRN** [comment]
```
#To Ordering my boxplot

#I have 

# "Agosto.Hibrido", "Junio.Hibrido", "Octubre.Hibrido", "Agosto.Nativo", "Junio.Nativo", "Octubre.Nativo"

#I want

#levels(data)<-("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo")

boxplot(Fisher ~ Time * Treatment, data = data)

var3<-c("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo")

#hacer un factor cuyos levels sean el order q yo quiero

mydata2<- factor(data, levels=levels(data)<-c("Junio.Hibrido", "Junio.Nativo", "Agosto.Hibrido", "Agosto.Nativo", "Octubre.Hibrido", "Octubre.Nativo"))

boxplot(Fisher ~ Time * Treatment, data = mydata2)

```

**Comment by AliciaMstt** [comment]
Solved! It was one of those silly things:

Originally you have *Time* and then *Treatment*, as follows:

```
anova<-aov(Fisher ~ Time * Treatment, data = data)
summary(anova)
boxplot(Fisher ~ Time * Treatment, data = data)
```

![image](https://user-images.githubusercontent.com/5412404/115904763-caa00b00-a42a-11eb-8fbd-a7d754f8d7c5.png)

What I did was simply to invert them, so that you have first *Treatment* and then *Time* as follows:

```
anova<-aov(Fisher ~ Treatment * Time, data = data)
summary(anova)
boxplot(Fisher ~ Treatment * Time , data = data, main="Treatment")
```

![image](https://user-images.githubusercontent.com/5412404/115903380-21a4e080-a429-11eb-9d35-5b8479973e3f.png)


You may also want to change the order of the months, so that it is Junio, Agosto, Octubre, instead of Agosto, Junio, Octubre. For this you need to change the order of the levels of `Time`. Like this:

```
# change Time levels order 
data$Time<-factor(data$Time, levels=c("Junio", "Agosto", "Octubre"))
# boxplot
boxplot(Fisher ~ Treatment * Time , data = data, main="Treatment")
```

![image](https://user-images.githubusercontent.com/5412404/115903801-a263dc80-a429-11eb-82ec-0c3bc9fb2c65.png)
